{
 "title": "VergeOS Dashboard",
 "tags": [
  "VergeOS",
  "monitoring",
  "infrastructure"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "label_values(vergeos_cluster_total_nodes,system_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vergeos_cluster_total_nodes{system_name=~\"$system\"}, cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "label_values(vergeos_drive_power_on_hours{system_name=~\"$system\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vergeos_cluster_total_nodes{system_name=~\"$system\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Online Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vergeos_cluster_online_nodes{system_name=~\"$system\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Running VMs and Tenant Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vergeos_cluster_running_machines{system_name=~\"$system\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_cluster_status{system_name=~\"$system\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "VSAN Redundancy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_redundant{system_name=~\"$system\"}",
     "legendFormat": "Tier {{tier}}"
    }
   ]
  },
  {
   "title": "VSAN Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vergeos_vsan_tier_used{system_name=~\"$system\"} / vergeos_vsan_tier_capacity{system_name=~\"$system\"}) * 100",
     "legendFormat": "Tier {{tier}}"
    }
   ]
  },
  {
   "title": "CPU % Overcommit",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vergeos_cluster_used_cores{system_name=~\"$system\", cluster=~\"$cluster\"} /\n vergeos_cluster_online_cores{system_name=~\"$system\", cluster=~\"$cluster\"}) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Used CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_cluster_used_cores{system_name=~\"$system\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_cluster_online_cores{system_name=~\"$system\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "RAM N+1",
   "type": "stat",
   "description": "Can I withstand a node failure without workloads being affected",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    vergeos_cluster_total_nodes{system_name=~\"$system\", cluster=~\"$cluster\"} > 0\n  and\n    vergeos_cluster_total_ram{system_name=~\"$system\", cluster=~\"$cluster\"} > 0\n  )\n  * on (system_name, cluster)\n  (\n    (vergeos_cluster_total_ram{system_name=~\"$system\", cluster=~\"$cluster\"} - vergeos_cluster_used_ram{system_name=~\"$system\", cluster=~\"$cluster\"})\n    /\n    (vergeos_cluster_total_ram{system_name=~\"$system\", cluster=~\"$cluster\"} / vergeos_cluster_total_nodes{system_name=~\"$system\", cluster=~\"$cluster\"})\n  )\n)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_cluster_used_ram{system_name=~\"$system\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_cluster_total_ram{system_name=~\"$system\", cluster=~\"$cluster\"} ",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (node_name, system_name) (\n  vergeos_node_cpu_core_usage{system_name=~\"$system\"}\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node CPU Temperature",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_node_core_temp{system_name=~\"$system\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "VSAN Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "VSAN Repairs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_tier_repairs{system_name=~\"$system\"}",
     "legendFormat": "Tier: {{tier}}"
    }
   ]
  },
  {
   "title": "VSAN Drives Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_drives_online{system_name=~\"$system\"}",
     "legendFormat": "Tier: {{tier}}"
    }
   ]
  },
  {
   "title": "VSAN Bad Drives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_bad_drives{system_name=~\"$system\"}",
     "legendFormat": "Tier: {{tier}}"
    }
   ]
  },
  {
   "title": "VSAN Tier Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_tier_capacity{system_name=~\"$system\"}",
     "legendFormat": "Tier {{tier}}"
    }
   ]
  },
  {
   "title": "VSAN Tier Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_tier_used{system_name=~\"$system\"}",
     "legendFormat": "Tier {{tier}}"
    }
   ]
  },
  {
   "title": "VSAN Tier Allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_tier_allocated{system_name=~\"$system\"}",
     "legendFormat": "Tier {{tier}}"
    }
   ]
  },
  {
   "title": "VSAN Deduplicated Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "suffix::1" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_vsan_tier_dedupe_ratio{system_name=~\"$system\"}",
     "legendFormat": "Tier {{tier}}"
    }
   ]
  },
  {
   "title": "Drive Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vergeos_drive_util{system_name=~\"$system\"}",
     "legendFormat": "{{drive_name}} ({{node_name}})"
    }
   ]
  },
  { "title": "vSAN Drive Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Power On Hours",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "vergeos_drive_power_on_hours{system_name=~\"$system\", node_name=~\"$node_name\"} / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Temperature",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vergeos_drive_temperature{system_name=~\"$system\"}",
     "legendFormat": "{{node_name}} {{drive_name}}"
    }
   ]
  },
  {
   "title": "Drive Service Time $node_name",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "repeat": "node_name",
   "targets": [
    {
     "expr": "vergeos_drive_service_time{system_name=~\"$system\"}",
     "legendFormat": "{{drive_name}} ms"
    }
   ]
  }
 ]
}