blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/verge-io/vergeos-exporter/blob/main/README.md
    about: Check out our documentation before creating an issue
